name: Webapp

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      # Install dependencies
      - name: Install Dependencies
        run: npm install
        working-directory: ./joyboy-webapp

      # Deploy step
      - name: Deploy
        run: npm run deploy
        working-directory: ./joyboy-webapp
